---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# cubicle

The `cubicle` R package is designed to create reproducible project structures with a consistent layout and customizable congifuration. 

---

## Installation

You can install `cubicle` with the following code.

``` r
devtools::install_github("bradyrippon/cubicle")
```

## Overview

Managing multiple projects at once demands a consistent organizational scheme and workflow to maintain consistency across your work. This often means creating the same file and folder construction over and over again so that all your R scripts and outputs can be found in a predictable place, or copy/pasting the same project template repeatedly. 

The `cubicle` package lets you generate a new project from a predefined template of files and folders in R and avoid the manual maintenance outlined above.

## Usage

### Basic example

Projects are generated using the `build_project()` function. 

```r
library(cubicle)

build_project(
  name = "my_project",
  path = "C:/Documents/Projects"
)
```
The code above creates an R project at:

```text
C:/Documents/Projects/my_project/
```
While `cubicle` comes with a recommended default project structure, everybody may already have their own personal organizational scheme that works for them! You are encouraged to test the default structures recommended by `cubicle`, though you can also save your own custom project template for repeated use. 

### Default project structure

```text
proj-name/
├── code/
│   ├── admin/
│   │   ├── functions/
│   │   └── libs.R
├── data/
│   └── raw/
├── documents/
│   └── prints/
│   │   └── published/
│   └── records/
│   │   └── published/
│   └── zips/
├── figures/
├── reports/
├── tags/
├── notes.docx
└── proj.Rproj
```

### Custom configuration

In addition to setting your own project template, you can also save a root parent directory if you expect to generally send your projects to the same local parent directory. The functions below will save these settings to your R profile and persist from session-to-session. 

```r
set_root("C:/Documents/Projects")
set_template("C:/Documents/Projects/my_template")
```

The folder specified in `set_template()` should contain the file/folder structure to be copied. You can view the current settings and reset these parameters to the package defaults with:

```r
# print template structure in console
show_template()

# view saved configuration paths
get_root()
get_template()

# reset to default
reset_root()
reset_template()
```

## License

MIT

## Author

Brady Rippon
