
#' Add a tag to the current project
#'
#' Creates a `.txt` file in the project's `tags/` folder.
#'
#' @param tag Character string giving the tag name.
#'
#' @export
add_tag <- function(tag) {

  if (!is.character(tag) || length(tag) != 1 || is.na(tag) || !nzchar(tag)) {
    cli::cli_abort("{.arg tag} must be a non-empty character string.")
  }

  tag <- .clean_tag(tag)
  if (tag == "#") {
    cli::cli_abort("Tag must contain at least one letter/number.")
  }

  project_root <- .active_project_root()

  if (is.null(project_root)) {
    cli::cli_abort(
      "Could not determine the current root. Run from inside an active R Project."
    )
  }

  tag_dir <- fs::path(project_root, "tags")
  fs::dir_create(tag_dir)

  tag_file <- fs::path(tag_dir, paste0(tag, ".txt"))
  writeLines("tag generated by the cubicle package", tag_file)

  cli::cli_alert_success("Added tag {.val {tag}}")
  invisible(tag_file)

} # --- add_tag()





# Utilities --------------------------------------------------

# -- clean user generated tag --
.clean_tag <- function(x) {

  x <- trimws(x)
  x <- tolower(x)
  x <- sub("^#+", "", x)          # delete existing prefix
  x <- gsub("[^a-z0-9]+", "-", x) # replace non-number/letter
  x <- gsub("^-+|-+$", "", x)     # delete extra hyphens

  paste0("#", x)                  # append to tag hash

} # --- .clean_tag()



# -- combine path/root directory --
.find_project_root <- function(start = getwd()) {

  current <- .normalize_path(start)

  repeat {
    rproj_file <- fs::dir_ls(current, regexp = "\\.Rproj$", type = "file")

    if (length(rproj_file) > 0) {
      return(current)
    }

    parent <- fs::path_dir(current)
    if (identical(parent, current)) {
      return(NULL)
    }

    current <- parent
  }

} # --- .find_project_root()



# -- check if inside an active R project --
.active_project_root <- function() {

  # find open RStudio project
  proj <- .get_active_rstudio_project()
  if (!is.null(proj)) {
    return(.normalize_path(proj))
  }

  .find_project_root()

} # --- .active_project_root()

